# Generated by Django 5.0.4 on 2024-08-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='amm_address',
            field=models.CharField(default='0x', max_length=100),
            preserve_default=False,
        ),
    ]
