# Generated by Django 5.0.4 on 2024-08-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
