# Generated by Django 5.0.4 on 2024-08-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userdetails_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='markets_created',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='markets_participated',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
