"""
Django settings for foreseer_backend project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-mw+!51e!sg_)wv&^h)$@d1nyo5yb&w!6qb5bwew5mw_$l^v2ww"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

CUSTOM_APPS = [
    "oms",
    "market",
    "user",
]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
] + CUSTOM_APPS

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
]

ROOT_URLCONF = "foreseer_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "foreseer_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # The origin for frontend
    "http://127.0.0.1:3000",
]

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True
REPUTATION_TOKEN_ADDRESS = "0xfF4f37AA9d561c63fd90596C6Db40B885FcC7D56"
MARKET_RESOLVER_ADDRESS = ""
CONDITIONAL_TOKEN_ADDRESS = "0xdC4665caB778D03D9D4Eb834a09946a779E8Efd8"
AMM_FACTORY_ADDRESS = "0xF5178A2Da05F7CeE9Fb17B6C5e37aCf85B9Eca56"
COLLATERAL_TOKEN_ADDRESS = "0x036CbD53842c5426634e7929541eC2318f3dCF7e"  # USDC
AMM_FACTORY_ABI = [
    {
        "inputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "constructor",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": True,
                "internalType": "address",
                "name": "creator",
                "type": "address",
            },
            {
                "indexed": False,
                "internalType": "address",
                "name": "lmsrMarketMaker",
                "type": "address",
            },
            {
                "indexed": False,
                "internalType": "address",
                "name": "pmSystem",
                "type": "address",
            },
            {
                "indexed": False,
                "internalType": "address",
                "name": "collateralToken",
                "type": "address",
            },
            {
                "indexed": False,
                "internalType": "bytes32[]",
                "name": "conditionIds",
                "type": "bytes32[]",
            },
            {
                "indexed": False,
                "internalType": "uint64",
                "name": "fee",
                "type": "uint64",
            },
            {
                "indexed": False,
                "internalType": "uint256",
                "name": "funding",
                "type": "uint256",
            },
        ],
        "name": "LMSRMarketMakerCreation",
        "type": "event",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "implementationMaster",
        "outputs": [
            {"internalType": "contract LMSRMarketMaker", "name": "", "type": "address"}
        ],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [
            {
                "internalType": "contract ConditionalTokens",
                "name": "pmSystem",
                "type": "address",
            },
            {
                "internalType": "contract IERC20",
                "name": "collateralToken",
                "type": "address",
            },
            {"internalType": "bytes32[]", "name": "conditionIds", "type": "bytes32[]"},
            {"internalType": "uint64", "name": "fee", "type": "uint64"},
            {
                "internalType": "contract Whitelist",
                "name": "whitelist",
                "type": "address",
            },
            {"internalType": "uint256", "name": "funding", "type": "uint256"},
        ],
        "name": "createLMSRMarketMaker",
        "outputs": [
            {
                "internalType": "contract LMSRMarketMaker",
                "name": "lmsrMarketMaker",
                "type": "address",
            }
        ],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
]


ERC_20_ABI = [
    {
        "constant": True,
        "inputs": [{"name": "_owner", "type": "address"}],
        "name": "balanceOf",
        "outputs": [{"name": "balance", "type": "uint256"}],
        "type": "function",
    }
]
